In [7]:
import numpy as np
x=np.arange(10).reshape(5,2)
y=range(5)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
model.predict([[13,14]])

array([6.5])

In [8]:
import pickle

with open ('LRmodel.pkl', 'wb') as f:
    pickle.dump(model,f)

In [10]:
with open ('LRmodel.pkl','rb') as f:
    saved_model = pickle.load(f)

In [11]:
saved_model

LinearRegression()

In [14]:
saved_model.predict([[10,11]])

array([5.])

In [17]:
import joblib

f1 = 'LRmodel.sav'
joblib.dump(model,f1)

joblib_model = joblib.load(f1)

joblib_model.predict([[1,2]])

array([0.5])

In [ ]:
from flask import Flask,jsonify,request
import pickle

app = Flask(__name__)

@app.route('/')
def hello():
    return "Hello World"

@app.route('/<int:x>/')
def x(x):
    print(x)




def check ():
    print (x1,"---",x2)
    fp=open('LRmodel.pkl','rb')
    saved_model = pickle.load(fp)
    
    predictedY = saved_model.predict([[10,11]])
    print("Output is ",predictedY)
    return "Y : "+str(predictedY[0])


app.run(host="0.0.0.0", port=106)

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:106
 * Running on http://192.168.196.184:106
Press CTRL+C to quit


In [10]:

def check (x1,x2):
    
    print (x1,"---",x2)
    fp=open('LRmodel.pkl','rb')
    saved_model = pickle.load(fp)
    
    predictedY = saved_model.predict([[x1,x2]])
    print("Output is ",predictedY)
    return "Y : "+str(predictedY[0])

check(10,11)

10 --- 11
Output is  [5.]


'Y : 5.0'